### ISSUE TITLE
Unable to click the save to decide png or share

### ISSUE THREAD

**Issue by 2217441** [iiumschedule/iium_schedule#105]
Also the schedules is cropped at the bottom when there's class at night

**Comment by iqfareez** [comment]
> Unable to click the save to decide png or share 

May I know which platform you're having this issue?

> Also the schedules is cropped at the bottom when there's class at night

Thank you for the report. I'll look a way to fix it.

**Comment by 2217441** [comment]
> May I know which platform you're having this issue?
It's on the Android platform

**Comment by iqfareez** [comment]
I'll check it out later

**Comment by iqfareez** [comment]
Fix in latest release #110
